development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: word_a_day_dev
  pool: 5
  username: word_a_day_dev
  password: trocar@123

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: word_a_day_prod
  pool: 5
  username: word_a_day_dev
  password: trocar@123
